repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pnpm prettier --write --ignore-unknown
        language: system
        types: [text]
        stages: [pre-commit]
      - id: tsc
        name: tsc
        entry: pnpm tsc --noEmit
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: eslint
        name: eslint
        entry: pnpm eslint --max-warnings=0
        language: system
        types: [ts, tsx]
        stages: [pre-commit]
