repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pnpm prettier --write --ignore-unknown
        language: system
        types: [text]
        stages: [pre-commit]
